### ISSUE TITLE
Typo found in the "around classes" section

### ISSUE THREAD

**Issue by AngieMoomin** [ariatemplates/usermanual#107]
Hello. 

I found a typo in the url http://ariatemplates.com/usermanual/latest/around_classes 

In the code snippet: /snippets/core/classes/IColorfulObject.js

It is written:
cb will be the 2nd atgument

It should be: **argument**

**Comment by divdavem** [comment]
@AngieMoomin Thank you for reporting this mistake. The correct text will appear in the documentation the next time it is deployed.
