### ISSUE TITLE
Another typo found in the "around classes" section

### ISSUE THREAD

**Issue by AngieMoomin** [ariatemplates/usermanual#108]
In the url http://ariatemplates.com/usermanual/latest/around_classes, when it talks about Dependencies .

It is written:
Aria Templates can handles 2 different kinds of dependencies

It should be: 
Aria Templates can **handle**

**Comment by divdavem** [comment]
@AngieMoomin Thank you for reporting this mistake. The correct text will appear in the documentation the next time it is deployed.
